name: AFUf GitHub Users

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:     # Allows the workflow to be run manually

jobs:
  follow-unfollow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Run follow-unfollow script
        env:
          GITHUB_USERNAME: ${{ secrets.USAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.USAGE_TOKEN }}
        run: |
          ./script.sh
